version: '3.8'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/todos
    depends_on:
      - db
    command: >
      bash -c "
        echo 'Waiting for database...' &&
        while ! nc -z db 5432; do
          sleep 0.1
        done &&
        echo 'Database is ready!' &&
        python -m app.db.init_db &&
        uvicorn app.main:app --host 0.0.0.0 --reload
      "

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=todos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
